### ISSUE TITLE
The custom integration gismeteo implements the forecast property or sets self._attr_forecast in a subclass of WeatherEntity.

### ISSUE THREAD

**Issue by aldanstar** [Limych/ha-gismeteo#182] opened 2024-01-16 10:40 UTC
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Это приведет к неисправностям в версии 2024.3.0. Пожалуйста, устраните эту проблему перед обновлением.

The custom integration gismeteo implements the forecast property or sets self._attr_forecast in a subclass of WeatherEntity.

Please create a bug report at https://github.com/Limych/ha-gismeteo/issues.

Once an updated version of gismeteo is available, install it and restart Home Assistant to fix this issue.

### Describe the solution you'd like

fix the  the forecast property , WeatherEntity

### Describe alternatives you've considered

No idea

### Additional context

No context

**Comment by ildar170975** [comment] 2024-01-16 10:43
duplicate of https://github.com/Limych/ha-gismeteo/issues/165

**Closed as completed** 2024-05-17 12:07 UTC
Labels: duplicate
